version: "3.3"
services:
    mongo:
        image: mongo:3.6
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        deploy:
            restart_policy:
                condition: on-failure
    app:
        image: webtimer
        ports: 
            - "3443:443"
        depends_on:
            - mongo
        environment:
            - NODE_ENV=production
            - MONGO_HOST=mongodb://mongo/
            - SERVER_PORT=443
            - SERVER_EXTERNAL_PORT=3443
            - SERVER_EXTERNAL_HOST=localhost
            #- SERVER_HOST=0.0.0.0
            #- SERVER_PFX_PATH=1.pfx
			#- MAIL_HOST=smtp.email.com
            #- MAIL_SECURE_PORT=465
            #- MAIL_AUTH_USER=example@email.com
            #- ABOUT_WEBSITE=http://yoursite.com
            #- LOGGER_LEVEL=warn
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 20s
        secrets:
            - AUTH_FACEBOOK_CLIENT_ID
            - AUTH_FACEBOOK_CLIENT_SECRET
            - SERVER_PFX_PASSWORD
            #- MAIL_AUTH_PASSWORD
volumes:
    mongo-data:
secrets:
    AUTH_FACEBOOK_CLIENT_ID:
        external: true
    AUTH_FACEBOOK_CLIENT_SECRET:
        external: true
    SERVER_PFX_PASSWORD:
        external: true
    #MAIL_AUTH_PASSWORD:
        #external: true
